 Hi all, I'm currently trying to run the matlab code from the DeepLearnToolbox, which is the test_example_DBN.m in the 'test's folder.However during running it encountered some error which is in the 'nnsetup' section. I'm not able to understand what the problem is and how to fix it. Need help to explain and teach me where the problem is and how to make it work, so that i can proceed from here. Thanks in advance..The error message as below:??? Attempted to access lmisys(5); index out of bounds because numel(lmisys)=4.
 First, read the available documentation on the Deep Learning Toolbox thoroughly. That may resolve your problem. Specifically, look through and run ‘caeexamples.m’, ‘mnist data’ and ‘runalltests.m’.If you are still having problems, it is probably best that you contact the author.
 This is because DeepLearnToolBox has an NeuralNetwork tool which is conflict with the Matlab inner NN toolbox.So you can solve this as following:File-SetPath-Add With Subfolders,select your toolbox path.Make sure the path of DeepLearnToolBox is in the top.After that ,try again.
